version: '3'
services:
  web:
    container_name: imapi_web
    platform: linux/x86_64 # M1チップ対応のため追記
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 9080:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    tty: true
    depends_on:
      - app
  app:
    container_name: imapi_app
    platform: linux/x86_64 # M1チップ対応のため追記
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: imapi_db
    platform: linux/x86_64 # M1チップ対応のため追記
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - ./.docker/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  mail:
    container_name: imapi_mail
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  db-data:
