version: "3.7"

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./../nest-ts
        target: /api
    ports:
      - "3000:3000"